sudo: false
language: cpp
compiler: clang
script: cd source/src && make
addons:
  apt:
    packages:
      - clang
      - make
      - automake
      - libsdl1.2-dev
      - libogg-dev
      - libsdl-image1.2-dev
      - libopenal-dev
      - libvorbis-dev
